import type { DatabaseDialect, SchemaDiagram, SchemaField, SchemaRelation, SchemaTable } from "../types/schema";

/** Imports conventional CREATE TABLE / INDEX DDL generated by common database tools. */
export function parseSqlDdl(source: string, dialect: DatabaseDialect): SchemaDiagram {
  const tables: SchemaTable[] = [];
  const pendingRelations: Array<{ source: string; sourceFields: string[]; target: string; targetFields: string[]; name: string; onDelete: SchemaRelation["onDelete"]; onUpdate: SchemaRelation["onUpdate"] }> = [];
  const tablePattern: RegExp = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([\w`"[\].]+)\s*\(([\s\S]*?)\)\s*;/gi;
  let match: RegExpExecArray | null;
  while ((match = tablePattern.exec(source))) {
    const name: string = cleanIdentifier(match[1]);
    const table: SchemaTable = { id: crypto.randomUUID(), name, x: 120 + tables.length % 3 * 360, y: 120 + Math.floor(tables.length / 3) * 260, width: 260, color: "#5f6ee8", comment: "", collapsed: false, locked: false, fields: [], indexes: [] };
    splitDefinitions(match[2]).forEach((definition: string) => {
      const primary: RegExpMatchArray | null = definition.match(/^PRIMARY\s+KEY\s*\(([^)]+)\)/i);
      const foreign: RegExpMatchArray | null = definition.match(/^(?:CONSTRAINT\s+([\w`"[\]]+)\s+)?FOREIGN\s+KEY\s*\(([^)]+)\)\s+REFERENCES\s+([\w`"[\].]+)\s*\(([^)]+)\)(.*)$/i);
      if (primary) { primary[1].split(",").map(cleanIdentifier).forEach((fieldName: string) => { const field: SchemaField | undefined = table.fields.find((item: SchemaField) => item.name === fieldName); if (field) field.primary = true; }); return; }
      if (foreign) { const tail: string = foreign[5]; pendingRelations.push({ source: name, sourceFields: foreign[2].split(",").map(cleanIdentifier), target: cleanIdentifier(foreign[3]), targetFields: foreign[4].split(",").map(cleanIdentifier), name: cleanIdentifier(foreign[1] ?? ""), onDelete: actionFrom(tail, "DELETE"), onUpdate: actionFrom(tail, "UPDATE") }); return; }
      const column: RegExpMatchArray | null = definition.match(/^([\w`"[\]]+)\s+(.+?)(?:\s+(NOT\s+NULL|NULL|DEFAULT\s+.+|PRIMARY\s+KEY|UNIQUE).*)?$/i);
      if (!column) return;
      const tail: string = definition.slice(column[1].length + column[2].length);
      table.fields.push({ id: crypto.randomUUID(), name: cleanIdentifier(column[1]), type: column[2].trim(), primary: /PRIMARY\s+KEY/i.test(tail), nullable: !/NOT\s+NULL|PRIMARY\s+KEY/i.test(tail), unique: /\bUNIQUE\b/i.test(tail), defaultValue: tail.match(/DEFAULT\s+(.+?)(?=\s+(?:NOT|UNIQUE|PRIMARY)|$)/i)?.[1]?.trim() ?? "", comment: "" });
    });
    tables.push(table);
  }
  const relations: SchemaRelation[] = pendingRelations.flatMap((item) => { const sourceTable: SchemaTable | undefined = tables.find((table: SchemaTable) => table.name === item.source); const targetTable: SchemaTable | undefined = tables.find((table: SchemaTable) => table.name === item.target); if (!sourceTable || !targetTable) return []; const sourceIds: string[] = item.sourceFields.map((name: string) => sourceTable.fields.find((field: SchemaField) => field.name === name)?.id).filter((id: string | undefined): id is string => Boolean(id)); const targetIds: string[] = item.targetFields.map((name: string) => targetTable.fields.find((field: SchemaField) => field.name === name)?.id).filter((id: string | undefined): id is string => Boolean(id)); if (!sourceIds.length || sourceIds.length !== targetIds.length) return []; return [{ id: crypto.randomUUID(), sourceTableId: sourceTable.id, sourceFieldIds: sourceIds, targetTableId: targetTable.id, targetFieldIds: targetIds, cardinality: "many-to-one", constraintName: item.name, onDelete: item.onDelete, onUpdate: item.onUpdate }]; });
  if (!tables.length) throw new Error("No CREATE TABLE statements were found.");
  return { dialect, enums: [], customTypes: [], notes: [], areas: [], tables, relations };
}

function splitDefinitions(value: string): string[] { const parts: string[] = []; let depth: number = 0; let start: number = 0; for (let index: number = 0; index < value.length; index += 1) { if (value[index] === "(") depth += 1; if (value[index] === ")") depth -= 1; if (value[index] === "," && depth === 0) { parts.push(value.slice(start, index).trim()); start = index + 1; } } parts.push(value.slice(start).trim()); return parts.filter(Boolean); }
function cleanIdentifier(value: string): string {
  const parts: string[] = value.trim().split(".").map((part: string) => part.replace(/^(?:\[|`|")|(?:\]|`|")$/g, ""));

  return parts.pop() ?? "";
}
function actionFrom(value: string, action: string): SchemaRelation["onDelete"] { const match: RegExpMatchArray | null = value.match(new RegExp(`ON\\s+${action}\\s+(NO\\s+ACTION|RESTRICT|CASCADE|SET\\s+NULL|SET\\s+DEFAULT)`, "i")); return (match?.[1]?.replace(/\s+/g, " ").toUpperCase() ?? "NO ACTION") as SchemaRelation["onDelete"]; }
